apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demo"
  template:
    metadata:
      labels:
        app: "demo"
    spec:
      containers:
        - name: "demo"
          image: "silviod92/demo:latest"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "demo"
spec:
  selector:
    app: "demo"
  ports:
    - protocol: "TCP"
      port: 8080
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discoverer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods"]
    verbs: ["create", "update", "get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-service-discoverer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: service-discoverer
  apiGroup: rbac.authorization.k8s.io

